/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Server;

import java.util.Vector;

import javax.swing.BoxLayout;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTextArea;

/**
 * 
 * @author sascha
 */
public class ServerMessagePanel extends javax.swing.JPanel {

	private JComboBox jComboBox1;
	private JButton jButton1;
	private JTextArea jTextArea;

	/**
	 * Creates new form LoggedInUserPanel
	 */
	public ServerMessagePanel() {
		initComponents();
		loadUsers();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jComboBox1 = new javax.swing.JComboBox();
		
		JPanel listPane = new JPanel();
		listPane.setLayout(new BoxLayout(listPane, BoxLayout.PAGE_AXIS));
		jTextArea= new javax.swing.JTextArea();
		jButton1=new javax.swing.JButton();
		jButton1.setText("Send");

		listPane.add(jComboBox1);
		listPane.add(jTextArea);
		listPane.add(jButton1);
		
		jScrollPane1.setViewportView(jTextArea);

	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	
	private javax.swing.JScrollPane jScrollPane1;

	// End of variables declaration//GEN-END:variables

	private void loadUsers() {
		validate();
		repaint();
	}
}
