/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Server;

import DBClasses.Article;
import java.util.Vector;
import javax.swing.DefaultListModel;
import messages.Pair;
import messages.ReducedUserData;

/**
 * 
 * @author sascha
 */
public class ServerArticlePanel extends javax.swing.JPanel {

	private Vector<Pair<Article, ReducedUserData>> articleList;

	/**
	 * Creates new form ServerArticleForm
	 */
	public ServerArticlePanel() {
		initComponents();
		loadArticles();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jList1 = new javax.swing.JList();
		jButton1 = new javax.swing.JButton();

		jScrollPane1.setViewportView(jList1);

		jButton1.setText("Manage Article");
		jButton1.setToolTipText("");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jButton1)
																.addGap(0,
																		0,
																		Short.MAX_VALUE))
												.addComponent(
														jScrollPane1,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														376, Short.MAX_VALUE))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										240, Short.MAX_VALUE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jButton1).addContainerGap()));
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		if (jList1.getSelectedIndex() != -1)
			new ArticleManagementForm(
					articleList.get(jList1.getSelectedIndex()))
					.setVisible(true);
	}// GEN-LAST:event_jButton1ActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JList jList1;
	private javax.swing.JScrollPane jScrollPane1;

	// End of variables declaration//GEN-END:variables

	private void loadArticles() {
		articleList = ServerCore.getArticleList();
		DefaultListModel listModel = new DefaultListModel();
		for (int i = 0; i < articleList.size(); i++) {
			Pair<Article, ReducedUserData> pair = articleList.get(i);
			String item = "[" + pair.left.getId() + "] - "
					+ pair.left.getShortDescription() + " by "
					+ pair.right.getName();
			listModel.addElement(item);
		}
		jList1.setModel(listModel);
		validate();
		repaint();
	}
}
