/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIClasses;

import java.util.Vector;

import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import messages.ArticleListAnswerPayload;
import messages.ArticleListMessageRequest;
import messages.IVBMessage;
import messages.OperationFailedAnswer;

import DBClasses.User;
import DBClasses.Article;
import HelpCLasses.ClientConnectionManager;
import HelpCLasses.ICSMessageEventReceiver;

/**
 *
 * @author sascha
 */
public class ClientArticleListPanel extends javax.swing.JPanel implements
	ICSMessageEventReceiver {

    private User user;
    private boolean showOffers;
    private Vector<Article> artVec;
    private ClientConnectionManager ccm;
    private JDialog dialog;
    private JLabel dialogLabel;
    private ClientMainFrame parent;

    /**
     * Creates new form ClientArticleDetailPanel
     * 
     * @param showOffers
     * @param user
     * @param parent
     */
    public ClientArticleListPanel(User user, boolean showOffers,
	    ClientMainFrame parent) {
	initComponents();
	this.user = user;
	this.showOffers = showOffers;
	this.parent = parent;
	if (showOffers)
	    loadOffers();
	else
	    loadOwnArticles();
    }

    private void loadOwnArticles() {
	ArticleListMessageRequest req = new ArticleListMessageRequest(
		user.getId(), showOffers);
	ccm.addMessage(req, this);
	dialog = new JDialog();
	dialog.setTitle("Waiting for Login");
	dialogLabel = new JLabel();
	dialogLabel.setText("Waiting to send Message...");
	dialog.add(dialogLabel);
	dialog.setModal(true);
	dialog.show();
    }

    private void loadOffers() {
	ArticleListMessageRequest req = new ArticleListMessageRequest(
		user.getId(), !showOffers);
	ccm.addMessage(req, this);
	dialog = new JDialog();
	dialog.setTitle("Waiting for Login");
	dialogLabel = new JLabel();
	dialogLabel.setText("Waiting to send Message...");
	dialog.add(dialogLabel);
	dialog.setModal(true);
	dialog.show();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

	jScrollPane1 = new javax.swing.JScrollPane();
	listComponent = new javax.swing.JList();
	detailButton = new javax.swing.JButton();
	actionButton = new javax.swing.JButton();
	cancelButton = new javax.swing.JButton();

	jScrollPane1.setViewportView(listComponent);

	detailButton.setText("Details");
	detailButton.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		detailButtonActionPerformed(evt);
	    }
	});

	actionButton.setText("Action");
	actionButton.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		actionButtonActionPerformed(evt);
	    }
	});

	cancelButton.setText("Cancel");
	cancelButton.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		cancelButtonActionPerformed(evt);
	    }
	});

	javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
	this.setLayout(layout);
	layout.setHorizontalGroup(layout
		.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		.addGroup(
			layout.createSequentialGroup()
				.addContainerGap()
				.addGroup(
					layout.createParallelGroup(
						javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(
							jScrollPane1,
							javax.swing.GroupLayout.DEFAULT_SIZE,
							662, Short.MAX_VALUE)
						.addGroup(
							layout.createSequentialGroup()
								.addComponent(
									detailButton)
								.addPreferredGap(
									javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(
									actionButton)
								.addPreferredGap(
									javax.swing.LayoutStyle.ComponentPlacement.RELATED,
									javax.swing.GroupLayout.DEFAULT_SIZE,
									Short.MAX_VALUE)
								.addComponent(
									cancelButton)))
				.addContainerGap()));
	layout.setVerticalGroup(layout
		.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		.addGroup(
			layout.createSequentialGroup()
				.addContainerGap()
				.addComponent(jScrollPane1,
					javax.swing.GroupLayout.PREFERRED_SIZE,
					356,
					javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(
					javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(
					layout.createParallelGroup(
						javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(detailButton)
						.addComponent(actionButton)
						.addComponent(cancelButton))
				.addContainerGap(
					javax.swing.GroupLayout.DEFAULT_SIZE,
					Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void detailButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_detailButtonActionPerformed
	Article art = getSelectedArticle();
	dialog = new JDialog();
	ClientArticleDetailPanel artPanel = new ClientArticleDetailPanel(user,
		art, showOffers, this);
	dialog.setContentPane(artPanel);
	dialog.setModal(true);
	dialog.show();
    }// GEN-LAST:event_detailButtonActionPerformed

    private Article getSelectedArticle() {
	// TODO Auto-generated method stub
	return null;
    }

    private void actionButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_actionButtonActionPerformed
	// TODO add your handling code here:
    }// GEN-LAST:event_actionButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelButtonActionPerformed
	// TODO add your handling code here:
    }// GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actionButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton detailButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listComponent;

    // End of variables declaration//GEN-END:variables
    @Override
    public void MessageSent() {
	dialogLabel.setText("Message Sent, Waiting for answer");
	dialog.invalidate();
    }

    @Override
    public void AnswerReceived(IVBMessage answer) {
	dialog.hide();
	switch (answer.MsgType()) {
	case ArticleListMessageAnswer:
	    ArticleListAnswerPayload payload = (ArticleListAnswerPayload) answer
		    .getPayload();
	    artVec = payload.getList();
	    loadList();
	    invalidate();
	    break;
	default:
	    break;
	}

    }

    private void loadList() {
	listComponent.setListData(artVec);
	invalidate();
    }

    @Override
    public void CommunicationError(IVBMessage answer) {
	JOptionPane.showMessageDialog(parent, "ERROR: "
		+ ((OperationFailedAnswer) answer).getReasons());
    }
}
