/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIClasses;

/**
 *
 * @author sascha
 */
public class ServerUserPanel extends javax.swing.JPanel {

    /**
     * Creates new form ServerUserPanel
     */
    public ServerUserPanel() {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

	jScrollPane1 = new javax.swing.JScrollPane();
	userList = new javax.swing.JList();
	userListLabel = new javax.swing.JLabel();
	actionButton = new javax.swing.JButton();
	conUserListLabel = new javax.swing.JLabel();
	jScrollPane2 = new javax.swing.JScrollPane();
	conUserList = new javax.swing.JList();
	cancelButton = new javax.swing.JButton();
	action2Button = new javax.swing.JButton();

	jScrollPane1.setViewportView(userList);

	userListLabel.setText("Users:");

	actionButton.setText("Action");
	actionButton.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		actionButtonActionPerformed(evt);
	    }
	});

	conUserListLabel.setText("Connected Users:");

	jScrollPane2.setViewportView(conUserList);

	cancelButton.setText("Cancel");
	cancelButton.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		cancelButtonActionPerformed(evt);
	    }
	});

	action2Button.setText("Action2");

	javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
	this.setLayout(layout);
	layout.setHorizontalGroup(layout
		.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		.addGroup(
			layout.createSequentialGroup()
				.addContainerGap()
				.addGroup(
					layout.createParallelGroup(
						javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
							layout.createSequentialGroup()
								.addGroup(
									layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(
											jScrollPane1,
											javax.swing.GroupLayout.PREFERRED_SIZE,
											358,
											javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(
											userListLabel))
								.addGap(18, 18,
									18)
								.addGroup(
									layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(
											layout.createSequentialGroup()
												.addComponent(
													conUserListLabel)
												.addGap(0,
													0,
													Short.MAX_VALUE))
										.addComponent(
											jScrollPane2,
											javax.swing.GroupLayout.DEFAULT_SIZE,
											362,
											Short.MAX_VALUE)))
						.addGroup(
							layout.createSequentialGroup()
								.addComponent(
									actionButton)
								.addPreferredGap(
									javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(
									action2Button)
								.addPreferredGap(
									javax.swing.LayoutStyle.ComponentPlacement.RELATED,
									javax.swing.GroupLayout.DEFAULT_SIZE,
									Short.MAX_VALUE)
								.addComponent(
									cancelButton)))
				.addContainerGap()));
	layout.setVerticalGroup(layout
		.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		.addGroup(
			layout.createSequentialGroup()
				.addContainerGap()
				.addGroup(
					layout.createParallelGroup(
						javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(userListLabel)
						.addComponent(conUserListLabel))
				.addPreferredGap(
					javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(
					layout.createParallelGroup(
						javax.swing.GroupLayout.Alignment.LEADING,
						false)
						.addComponent(
							jScrollPane2,
							javax.swing.GroupLayout.DEFAULT_SIZE,
							399, Short.MAX_VALUE)
						.addComponent(jScrollPane1))
				.addPreferredGap(
					javax.swing.LayoutStyle.ComponentPlacement.RELATED,
					24, Short.MAX_VALUE)
				.addGroup(
					layout.createParallelGroup(
						javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(actionButton)
						.addComponent(cancelButton)
						.addComponent(action2Button))
				.addContainerGap()));
    }// </editor-fold>//GEN-END:initComponents

    private void actionButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_actionButtonActionPerformed
	// TODO add your handling code here:
    }// GEN-LAST:event_actionButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelButtonActionPerformed
	// TODO add your handling code here:
    }// GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton action2Button;
    private javax.swing.JButton actionButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JList conUserList;
    private javax.swing.JLabel conUserListLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList userList;
    private javax.swing.JLabel userListLabel;
    // End of variables declaration//GEN-END:variables
}
