/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIClasses;

/**
 *
 * @author sascha
 */
public class ServerArticlePanel extends javax.swing.JPanel {

    /**
     * Creates new form ServerArticlePanel
     */
    public ServerArticlePanel() {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

	jScrollPane1 = new javax.swing.JScrollPane();
	articleList = new javax.swing.JList();
	actionButton = new javax.swing.JButton();
	cancelButton = new javax.swing.JButton();
	action2Button = new javax.swing.JButton();

	jScrollPane1.setViewportView(articleList);

	actionButton.setText("Action");
	actionButton.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		actionButtonActionPerformed(evt);
	    }
	});

	cancelButton.setText("Cancel");
	cancelButton.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		cancelButtonActionPerformed(evt);
	    }
	});

	action2Button.setText("Action2");
	action2Button.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		action2ButtonActionPerformed(evt);
	    }
	});

	javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
	this.setLayout(layout);
	layout.setHorizontalGroup(layout
		.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		.addGroup(
			layout.createSequentialGroup()
				.addContainerGap()
				.addGroup(
					layout.createParallelGroup(
						javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(
							jScrollPane1,
							javax.swing.GroupLayout.DEFAULT_SIZE,
							716, Short.MAX_VALUE)
						.addGroup(
							layout.createSequentialGroup()
								.addComponent(
									actionButton)
								.addPreferredGap(
									javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(
									action2Button)
								.addPreferredGap(
									javax.swing.LayoutStyle.ComponentPlacement.RELATED,
									javax.swing.GroupLayout.DEFAULT_SIZE,
									Short.MAX_VALUE)
								.addComponent(
									cancelButton)))
				.addContainerGap()));
	layout.setVerticalGroup(layout
		.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		.addGroup(
			layout.createSequentialGroup()
				.addContainerGap()
				.addComponent(jScrollPane1,
					javax.swing.GroupLayout.DEFAULT_SIZE,
					450, Short.MAX_VALUE)
				.addPreferredGap(
					javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(
					layout.createParallelGroup(
						javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(actionButton)
						.addComponent(cancelButton)
						.addComponent(action2Button))
				.addContainerGap()));
    }// </editor-fold>//GEN-END:initComponents

    private void actionButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_actionButtonActionPerformed
	// TODO add your handling code here:
    }// GEN-LAST:event_actionButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelButtonActionPerformed
	// TODO add your handling code here:
    }// GEN-LAST:event_cancelButtonActionPerformed

    private void action2ButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_action2ButtonActionPerformed
	// TODO add your handling code here:
    }// GEN-LAST:event_action2ButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton action2Button;
    private javax.swing.JButton actionButton;
    private javax.swing.JList articleList;
    private javax.swing.JButton cancelButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
