/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * 
 * @author sascha
 */
public class ClientMainFrame extends javax.swing.JFrame implements
		IClientGUIListener {

	private ClientCore core;
	private boolean waitForLogout;
	private Object author = "Sascha Tetkov";
	private String version = "0.1.0";

	/**
	 * Creates new form ClientMainFrame
	 */
	public ClientMainFrame() {
		initComponents();
		core = new ClientCore();
		confirmUserItem.setEnabled(true);
		logoutItem.setEnabled(false);
		myArticleItem.setEnabled(false);
		newArticleItem.setEnabled(false);
		newUserItem.setEnabled(true);
		offersItem.setEnabled(false);
		// quitItem;
		userDataItem.setEnabled(false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		loginMenuItem = new javax.swing.JMenuItem();
		newUserItem = new javax.swing.JMenuItem();
		confirmUserItem = new javax.swing.JMenuItem();
		jSeparator4 = new javax.swing.JPopupMenu.Separator();
		userDataItem = new javax.swing.JMenuItem();
		myArticleItem = new javax.swing.JMenuItem();
		offersItem = new javax.swing.JMenuItem();
		newArticleItem = new javax.swing.JMenuItem();
		jSeparator2 = new javax.swing.JPopupMenu.Separator();
		logoutItem = new javax.swing.JMenuItem();
		jSeparator3 = new javax.swing.JPopupMenu.Separator();
		quitItem = new javax.swing.JMenuItem();
		jSeparator1 = new javax.swing.JPopupMenu.Separator();
		jMenu2 = new javax.swing.JMenu();
		aboutItem = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setMinimumSize(new java.awt.Dimension(800, 600));
		setName("clientMainFrame"); // NOI18N

		jMenu1.setText("Client");

		loginMenuItem.setText("Login");
		loginMenuItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				loginMenuItemActionPerformed(evt);
			}
		});
		jMenu1.add(loginMenuItem);

		newUserItem.setText("New User");
		newUserItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				newUserItemActionPerformed(evt);
			}
		});
		jMenu1.add(newUserItem);

		confirmUserItem.setText("ConfirmUser");
		confirmUserItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				confirmUserItemActionPerformed(evt);
			}
		});
		jMenu1.add(confirmUserItem);
		jMenu1.add(jSeparator4);

		userDataItem.setText("User");
		userDataItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				userDataItemActionPerformed(evt);
			}
		});
		jMenu1.add(userDataItem);

		myArticleItem.setText("My Articles");
		myArticleItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				myArticleItemActionPerformed(evt);
			}
		});
		jMenu1.add(myArticleItem);

		offersItem.setText("Offers");
		offersItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				offersItemActionPerformed(evt);
			}
		});
		jMenu1.add(offersItem);

		newArticleItem.setText("New Article");
		newArticleItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				newArticleItemActionPerformed(evt);
			}
		});
		jMenu1.add(newArticleItem);
		jMenu1.add(jSeparator2);

		logoutItem.setText("Logout");
		logoutItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				logoutItemActionPerformed(evt);
			}
		});
		jMenu1.add(logoutItem);
		jMenu1.add(jSeparator3);

		quitItem.setText("Quit");
		quitItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				quitItemActionPerformed(evt);
			}
		});
		jMenu1.add(quitItem);
		jMenu1.add(jSeparator1);

		jMenuBar1.add(jMenu1);

		jMenu2.setText("Help");

		aboutItem.setText("About");
		aboutItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				aboutItemActionPerformed(evt);
			}
		});
		jMenu2.add(aboutItem);

		jMenuBar1.add(jMenu2);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 400,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 279,
				Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void loginMenuItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_loginMenuItemActionPerformed
		LoginPanel panel = new LoginPanel(core, this);
		this.setContentPane(panel);
		validate();
		repaint();
	}// GEN-LAST:event_loginMenuItemActionPerformed

	private void newUserItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_newUserItemActionPerformed
		CreateNewUserPanel panel = new CreateNewUserPanel(core, this, true);
		this.setContentPane(panel);
		validate();
		repaint();
	}// GEN-LAST:event_newUserItemActionPerformed

	private void confirmUserItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_confirmUserItemActionPerformed
		ConfirmUserPanel panel = new ConfirmUserPanel(core, this);
		this.setContentPane(panel);
		validate();
		repaint();
	}// GEN-LAST:event_confirmUserItemActionPerformed

	private void myArticleItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_myArticleItemActionPerformed
		ArticleForm panel = new ArticleForm(core, this, true);
		this.setContentPane(panel);
		validate();
		repaint();
	}// GEN-LAST:event_myArticleItemActionPerformed

	private void offersItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_offersItemActionPerformed
		ArticleForm panel = new ArticleForm(core, this, false);
		this.setContentPane(panel);
		validate();
		repaint();
	}// GEN-LAST:event_offersItemActionPerformed

	private void newArticleItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_newArticleItemActionPerformed
		ArticleDetailFrame adf = new ArticleDetailFrame();
		adf.fillFields(null, core, true);
		adf.setVisible(true);
	}// GEN-LAST:event_newArticleItemActionPerformed

	private void userDataItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_userDataItemActionPerformed
		CreateNewUserPanel panel = new CreateNewUserPanel(core, this, false);
		this.setContentPane(panel);
		validate();
		repaint();
	}// GEN-LAST:event_userDataItemActionPerformed

	private void logoutItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_logoutItemActionPerformed
		core.Logout(core.getUser().getId(), this);
                backToLogin();
	}// GEN-LAST:event_logoutItemActionPerformed

	private void quitItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_quitItemActionPerformed
		waitForLogout = true;
		this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		if (core.getUser() != null) {
			core.Logout(core.getUser().getId(), this);
		} else {
			this.setVisible(false);
			this.dispose();
			System.exit(0);
		}
	}// GEN-LAST:event_quitItemActionPerformed

	private void aboutItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_aboutItemActionPerformed
		JOptionPane.showMessageDialog(null, "Verkaufsboerse - Client - Ver."
				+ this.version + "\nby " + this.author);
	}// GEN-LAST:event_aboutItemActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ClientMainFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ClientMainFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ClientMainFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ClientMainFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ClientMainFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JMenuItem aboutItem;
	private javax.swing.JMenuItem confirmUserItem;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JPopupMenu.Separator jSeparator1;
	private javax.swing.JPopupMenu.Separator jSeparator2;
	private javax.swing.JPopupMenu.Separator jSeparator3;
	private javax.swing.JPopupMenu.Separator jSeparator4;
	private javax.swing.JMenuItem loginMenuItem;
	private javax.swing.JMenuItem logoutItem;
	private javax.swing.JMenuItem myArticleItem;
	private javax.swing.JMenuItem newArticleItem;
	private javax.swing.JMenuItem newUserItem;
	private javax.swing.JMenuItem offersItem;
	private javax.swing.JMenuItem quitItem;
	private javax.swing.JMenuItem userDataItem;

	// End of variables declaration//GEN-END:variables

	void LoginSuccesfull() {
		String message = "Welcome " + core.getUser().getName() + " "
				+ core.getUser().getSurname() + "!";
		JOptionPane.showMessageDialog(null, message);

		ArticleForm panel = new ArticleForm(core, this, false);
		this.setContentPane(panel);

		// loginMenuItem.setEnabled(false);
		confirmUserItem.setEnabled(false);
		logoutItem.setEnabled(true);
		myArticleItem.setEnabled(true);
		newArticleItem.setEnabled(true);
		newUserItem.setEnabled(false);
		offersItem.setEnabled(true);
		// quitItem;
		userDataItem.setEnabled(true);
		validate();
		repaint();

	}

	void backToStart() {
		ArticleForm panel = new ArticleForm(core, this, false);
		this.setContentPane(panel);
		validate();
		repaint();

	}

	@Override
	public void confirmMessageSent() {
		if (waitForLogout) {
			this.setVisible(false);
			this.dispose();
			System.exit(0);
		}

	}

	@Override
	public void positiveAnswerReceived(Object payload) {
		// throw new UnsupportedOperationException("Not supported yet."); //To
		// change body of generated methods, choose Tools | Templates.
	}

	@Override
	public void failureAnswerReceived(Object payload) {
		// throw new UnsupportedOperationException("Not supported yet."); //To
		// change body of generated methods, choose Tools | Templates.
	}

	@Override
	public void communicationErrorReceived(Object payload) {
		// throw new UnsupportedOperationException("Not supported yet."); //To
		// change body of generated methods, choose Tools | Templates.
	}

    public void backToLogin() {
        		LoginPanel panel = new LoginPanel(core, this);
		this.setContentPane(panel);
		confirmUserItem.setEnabled(true);
		logoutItem.setEnabled(false);
		myArticleItem.setEnabled(false);
		newArticleItem.setEnabled(false);
		newUserItem.setEnabled(true);
		offersItem.setEnabled(false);
		// quitItem;
		userDataItem.setEnabled(false);
		validate();
		repaint();
    }
}
